version: '3'

services:

  # client
  # server

  # messaging queue
  mq-standalone:
    image: apachepulsar/pulsar
    expose:
      - 8080
      - 6650
    environment:
      - BOOKIE_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone --advertised-address mq-standalone"

  # dashboard for mq
  mq-dashboard:
    image: apachepulsar/pulsar-dashboard
    depends_on:
      - mq-standalone
    ports:
      - "80:80"
    environment:
      - SERVICE_URL=http://mq-standalone:8080


  # database
  database:
    image: postgres
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=password
    # ports:
    #   - 5432:5432
